### ISSUE TITLE
CH Term dependency

### ISSUE THREAD

**Issue by ziegm** [hl7ch/ch-term#101]
By defining the **CH Term dependency** in the sushi-config.yaml this way... 
```
dependencies:
  hl7.terminology.r4:
    uri: http://terminology.hl7.org/ImplementationGuide/hl7.terminology
    version: 6.3.0
  hl7.fhir.uv.ips: 2.0.0-ballot
  ch.fhir.ig.ch-core: current
  ch.fhir.ig.ch-term: 3.1.x
```
... the ig resource (dependsOn) is generated like this (and this causes an error) -> package in the uri:
``` json
  {
    "id" : "ch_fhir_ig_ch_core",
    "uri" : "http://fhir.ch/ig/ch-core/ImplementationGuide/ch.fhir.ig.ch-core",
    "packageId" : "ch.fhir.ig.ch-core",
    "version" : "current"
  },
  {
    "id" : "ch_fhir_ig_ch_term",
    "uri" : "http://fhir.org/packages/ch.fhir.ig.ch-term/ImplementationGuide/ch.fhir.ig.ch-term",
    "packageId" : "ch.fhir.ig.ch-term",
    "version" : "3.1.x"
  }
```

Do we somewhere have an issue with the package registry or what could be the reason (terminology server)? @oliveregger @ralych 

***

(As a workaround) It can be fixed in the IG sushi-config.yaml like this:
```
  ch.fhir.ig.ch-term: 
    uri: http://fhir.ch/ig/ch-term/ImplementationGuide/ch.fhir.ig.ch-term
    version: 3.1.x
```
``` json
  {
    "id" : "ch_fhir_ig_ch_term",
    "uri" : "http://fhir.ch/ig/ch-term/ImplementationGuide/ch.fhir.ig.ch-term",
    "packageId" : "ch.fhir.ig.ch-term",
    "version" : "3.1.x"
  }
```
